name: Compile AHK to EXE
run-name: Compiling .ahk file to .exe binary
on: [push]
jobs:
  Build-Exe:
    name: Compile
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile with Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: UUR_Ultimate_Uma_Reroller.ahk
          out: UUR.exe
          icon: icon.ico

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binary
          path: ${{ steps.ahk2exe.outputs.binary }}
