name: Compile AHK to EXE
run-name: Compiling .ahk file to .exe binary
on: [push]
jobs:
  Build-Exe:
    name: Compile
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile with Ahk2Exe
        uses: benmusson/ahk2exe-action@v1
        with:
          in: UUR_Ultimate_Uma_Reroller.ahk
          out: UUR.exe
          icon: icon.ico
          target: x64
          # compression: upx
          ahk-tag: v1.1.37.02

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binary
          path: UUR.exe
